plugin_dirs = ['/home/alpha/.local/share/bottles/bottles/spitfire/drive_c/Program Files/Common Files/VST3']
vst2_location = 'centralized'
no_verify = false
blacklist = []

[last_known_config]
wine_version = 'wine-8.13 (Staging)'
yabridge_host_hash = -3455544459850266564
